FROM jackpine/biketag-api:latest
MAINTAINER Michael Kirk <michael@jackpine.me>

# These changes are intended to make the production Docker image ammenable to
# developing within a container

ENV HOME /root

CMD ["/sbin/my_init"]

# change app users id to coincide with mounted filesystem (using boot2docker)
RUN sed -i s/app:x:9999/app:x:1000/ /etc/passwd
RUN chown -R app /home/app

# Don't install gems as root, and don't put them in the app directory
RUN mkdir /home/app/.bundle
ADD config/containers/api-dev/conf/bundle-config /home/app/.bundle/config
ADD config/containers/api-dev/conf/bash-aliases /home/app/.bash_aliases

